random_seed: 0
data_path: data
gpu_id: 1
log_port: 8081
encoder_model_path: "models/autoencoder_pretrained/encoder.pt"
gan_discriminator_model_path: "models/gan/gan_discriminator.pt"
gan_decoder_model_path: "models/gan/gan_decoder.pt"
training:
  num_epochs: 100
  num_sample: 6
  noise_dim: 2
  learning_rate: 0.0002
  report_feq: 10
  batch_size: 8
  # Number of discriminator steps per generator step
  discrim_steps_per_gen: 3
  # Number of training stages  
  epochs_per_stage: 25