random_seed: 0
data_path: data
gpu_id: 1
log_port: 8081
forward_model_encoder_path: models/forward_model/forward_encoder.pt
forward_model_decoder_path: models/forward_model/forward_decoder.pt
image_encoder_model_path: models/image_autoencoder/encoder.pt
gan_discriminator_model_path: models/gan/gan_discriminator.pt
gan_decoder_model_path: models/gan/gan_decoder.pt
# Training parameters
training:
  num_epochs: 100
  num_sample: 6
  noise_dim: 2
  learning_rate: 0.0002
  report_feq: 10
  batch_size: 8
  # Number of discriminator steps per generator step
  discrim_steps_per_gen: 3
  # Number of training stages  
  epochs_per_stage: 25
# Evaluation parameters
evaluation:
  batch_size: 8
  num_sample: 1
  noise_dim: 2  